# site settings
title: jusmi
subtitle: 
email: albert@jvsmi.com
description: I'm a freelance motion and graphics designer with a passion for creating unique and exciting visuals!
baseurl: # the subpath of your site, e.g. /blog
url: https://jvsmi.com # the base hostname & protocol for your site
author:


# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/jusmiart/
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/_jusmi_

# build settings
markdown: kramdown

sass:
  style: compressed
